apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-spectrum-scale-lt
provisioner: csi-spectrum-scale
parameters:
    volBackendFs: "gpfs0"
    volDirBasePath: "pvfileset/lwdir"
reclaimPolicy: Delete

