apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset-dependent
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    clusterId: "7118073361626808055"
    filesetType: "dependent"
    parentFileset: "pvc-9c93ffc6-b113-47b4-bbb4-29306f567f2b"
reclaimPolicy: Delete
